# docker-compose.yml
services:
  db:
    image: postgres:15-alpine
    container_name: robot_agricola_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: robot_agricola_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: app/server/Dockerfile
    container_name: robot_agricola_backend
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - db
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: app/client/Dockerfile
      # Inyección de variables dinámicas al frontend en tiempo de compilación
      args:
        VITE_API_URL: ${VITE_API_URL:-/api}
        VITE_SOCKET_URL: ${VITE_SOCKET_URL:-/}
    container_name: robot_agricola_frontend
    ports:
      - "8080:8080" # Nginx Unprivileged en 8080
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:
