server {
    # Escuchamos en el puerto 8080 (requerido por imágenes sin root)
    listen 8080;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # 1. OPTIMIZACIÓN: Activar compresión Gzip para ahorrar ancho de banda
    gzip on;
    gzip_vary on;
    gzip_min_length 10240;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;

    # 2. FIX REACT ROUTER: El "Muro" anti-404
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 3. CACHÉ INTELIGENTE: Archivos estáticos de Vite (js, css, imágenes) cacheados por 1 año
    location ~* \.(?:css|js|jpg|svg|png|gif|ico|webp|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    # 4. ANTI-CACHÉ: El index.html NUNCA se cachea. Así siempre ven la última versión de tu código
    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }

    # Redirección de errores críticos del servidor
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}