# Identificadores obligatorios

sonar.projectKey=andresveracachoo_aplicacion-robot-agricola
sonar.organization=andresveracachoo

# Nombre de tu proyecto
sonar.projectName=aplicacion-robot-agricola

# Carpetas de código fuente que DEBEN ser analizadas
sonar.sources=src,server,database

# Archivos y carpetas que DEBEN ser ignoradas por el escáner
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.css,**/*.svg

# Ayuda a Sonar a entender que usas tanto React (browser) como Node (node)
sonar.javascript.environments=browser,node

# Si en el futuro añado test
# sonar.javascript.lcov.reportPaths=coverage/lcov.info