# Configuración principal de identificación en SonarCloud
sonar.projectKey=andresveracachoo_aplicacion-robot-agricola
sonar.organization=andresveracachoo
sonar.sourceEncoding=UTF-8

# Definimos explícitamente que la aplicación es un Monorepo compuesto por dos partes
sonar.modules=client,server

# Ruta al reporte único unificado de coverage generado por el script en la raíz
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Configuracion del frontend
client.sonar.projectName=Frontend
client.sonar.projectBaseDir=app/client

# Indicamos dónde está el código y dónde están las pruebas del frontend
client.sonar.sources=src
client.sonar.tests=src

# Filtramos qué archivos se deben evaluar como tests y cuáles ignorar en la nota final
client.sonar.test.inclusions=**/*.test.js,**/*.test.jsx
client.sonar.exclusions=**/*.test.js,**/*.test.jsx,**/node_modules/**,**/dist/**,**/public/**,**/coverage/**,src/main.jsx,src/setupTests.js,vite.config.js

# Ruta al reporte de coverage generado por Vite/Jest (comentado a favor del global)
# client.sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Configuracion del backend
server.sonar.projectName=Backend
server.sonar.projectBaseDir=app/server

# Indicamos la carpeta principal del código del servidor
server.sonar.sources=src

# El backend tiene pruebas unitarias (en src) y pruebas E2E (en tests)
server.sonar.tests=src,tests

# Filtramos los archivos de configuración, de arranque y scripts para que no bajen el coverage
server.sonar.test.inclusions=**/*.test.js,**/*.test.jsx
server.sonar.exclusions=**/*.test.js,**/*.test.jsx,**/node_modules/**,**/coverage/**,src/scripts/**,src/simulator/index.js,src/index.js,jest.config.js,jest.e2e.config.js

# Agrupamos ambos reportes (Unitario y E2E) para que Sonar unifique la nota del backend (comentado a favor del global)
# server.sonar.javascript.lcov.reportPaths=coverage/unit/lcov.info,coverage/e2e/lcov.info