# Identificadores obligatorios
sonar.projectKey=tu_project_key_de_sonarcloud
sonar.organization=tu_organizacion_de_github

# Carpetas que Sonar DEBE analizar (tu frontend y tu backend)
sonar.sources=src,server

# Carpetas y archivos que Sonar DEBE IGNORAR 
sonar.exclusions=**/node_modules/**, dist/**, **/*.test.js, **/*.test.jsx

# Si en el futuro añado test
# sonar.javascript.lcov.reportPaths=coverage/lcov.info