sequenceDiagram
    autonumber
    participant Time as NodeJS (setInterval)
    participant Sim as simulator.js
    participant DB as Prisma (DB)
    participant WS as Socket.io
    participant Z as Zustand (Frontend)

    Time->>Sim: Dispara Tick (cada X ms)
    Sim->>Sim: Calcula Radiación Solar f(fecha, hora)
    Sim->>Sim: Calcula consumo de batería (IDLE/WORKING)
    Sim->>Sim: Obtiene coord. interpolada del pathfinding
    Sim->>Sim: Inyecta NPK y pH con semilla criptográfica
    Sim->>DB: INSERT INTO robot_datos (Bulk / Queue)
    Sim->>DB: DELETE FROM robot_datos ... (Búfer circular)
    Sim->>WS: io.emit('robot:new_data', payload)
    WS-->>Z: Recepción asíncrona de socket
    Z->>Z: set({ telemetry: payload })
    Z-->>Z: Componentes reactivos re-renderizan
