name: CI And SonarCloud Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-test-analyze:
    name: Build, Test & Sonar Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Obligatorio para SonarQube

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install Monorepo Dependencies
        run: npm ci

      # Separamos los tests y les ponemos continue-on-error para que no aborten el pipeline
      - name: Run Frontend Tests & Coverage
        working-directory: ./app/client
        continue-on-error: true 
        run: npm run test:cov

      - name: Run Backend Unit Tests & Coverage
        working-directory: ./app/server
        continue-on-error: true
        run: npm run test:unit:cov

      - name: Run Backend E2E Tests & Coverage
        working-directory: ./app/server
        continue-on-error: true
        run: npm run test:e2e:cov

      - name: Fix LCOV file paths
        if: always() # Obligamos a que se ejecute siempre
        run: |
          # 1. Quitar rutas absolutas de la máquina virtual de GitHub
          sed -i "s|$(pwd)/||g" app/client/coverage/lcov.info || true
          sed -i "s|$(pwd)/||g" app/server/coverage/unit/lcov.info || true
          sed -i "s|$(pwd)/||g" app/server/coverage/e2e/lcov.info || true
          
          # 2. Corregir rutas relativas (El problema del Monorepo)
          sed -i -E "s|SF:src/|SF:app/client/src/|g" app/client/coverage/lcov.info || true
          sed -i -E "s|SF:src/|SF:app/server/src/|g" app/server/coverage/unit/lcov.info || true
          sed -i -E "s|SF:src/|SF:app/server/src/|g" app/server/coverage/e2e/lcov.info || true

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@30dbe5c9eeccb106afb2590dcb61f7a05ffbee14
        if: always() # Obligamos a que Sonar se ejecute siempre para poder ver los fallos en la web
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}